# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addres', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=40, verbose_name='交易账号')),
                ('enabled', models.IntegerField(choices=[[0, '未启用'], [1, '启用']], default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=40, verbose_name='账户')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('license', models.CharField(max_length=30, verbose_name='许可证')),
                ('appid', models.CharField(max_length=20, verbose_name='ApppID')),
                ('userid', models.CharField(max_length=20, verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=36, null=True, verbose_name='邮箱')),
                ('enabled', models.IntegerField(choices=[[0, '未启用'], [1, '启用']], default=0, verbose_name='状态')),
                ('jurisdiction', models.IntegerField(choices=[[1, '普通用户'], [2, '内部用户'], [3, '管理员']], default=1, verbose_name='用户权限')),
                ('creationTime', models.CharField(max_length=12, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(auto_now_add=True, verbose_name='填写日期')),
                ('date', models.DateField(verbose_name='所属工作日期')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(max_length=300, verbose_name='详细内容')),
                ('belonged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Users', verbose_name='所属用户')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='belonged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Users', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='simulationaccount',
            name='belonged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Users', verbose_name='所属用户'),
        ),
    ]
