# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-10 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180822_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infobody',
            options={'ordering': ('startDate',)},
        ),
    ]
